services:
    db:
        image: postgres:16-alpine
        container_name: next_prisma_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
        ports:
            - "5032:5432" # host:container
        volumes:
            - db_data:/var/lib/postgresql/data

    nextjs:
        build: .
        container_name: next_prisma_app
        restart: always
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
            NODE_ENV: development
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    db_data:
